server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=277353

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Deklarasi RabbitMQ otomatis saat startup
spring.rabbitmq.dynamic=true

logging.level.org.springframework.amqp=DEBUG
logging.level.org.springframework.rabbit=DEBUG